ExamenAdoNetJavierLopez/Models/ErrorViewModel.cs
using System;

namespace ExamenAdoNetJavierLopez.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamenAdoNetJavierLopez/Models/Genero.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenAdoNetJavierLopez.Models
{
    public class Genero
    {
        public int IdGenero { set; get; }
        public String Gnombre { set; get; }
    }
}

ExamenAdoNetJavierLopez/Models/Libro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenAdoNetJavierLopez.Models
{
    public class Libro
    {
        public int IdLibro { set; get; }
        public String Titulo { set; get; }
        public String Autor { get; set; }
        public String Sinopsis { set; get; }
        public String Imagen { set; get; }
        public int IdGenero { set; get; }
    }
}

ExamenAdoNetJavierLopez/Controllers/GenerosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExamenAdoNetJavierLopez.Data;
using ExamenAdoNetJavierLopez.Models;

namespace ExamenAdoNetJavierLopez.Controllers
{
    public class GenerosController : Controller
    {
        LibrosContext context;

        public GenerosController()
        {
            this.context = new LibrosContext();
        }

        public IActionResult Genero()
        {
            List<Genero> generos = this.context.getGeneros();
            return View(generos);
        }
        
        public IActionResult creaGenero()
        {
            return View();
        }
        [HttpPost]
        public IActionResult creaGenero(Genero gen)
        {
            this.context.CreaGenero(gen.Gnombre);
            return RedirectToAction("Genero");
        }
        public IActionResult eliminaGenero(int idgenero)
        {
            this.context.EliminaGenero(idgenero);
            return RedirectToAction("Genero");
        }

        public IActionResult buscaLibros()
        {
            List<Genero> generos = this.context.getGeneros();
            ViewBag.Libros = this.context.getLibrosporGenero(-5);
            return View(generos);
        }
        [HttpPost]
        public IActionResult buscaLibros(Genero gen)
        {
            if (ViewBag.GeneroNombre != null)
            {
                gen.Gnombre = ViewBag.GeneroNombre;
            }
            List<Genero> generos = this.context.getGeneros();
            ViewBag.Libros = this.context.getLibrosNombreGenero(gen.Gnombre);
            ViewBag.GeneroNombre = gen.Gnombre;
            return View(generos);
        }
    }
}

ExamenAdoNetJavierLopez/Controllers/HomeController.cs
using ExamenAdoNetJavierLopez.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenAdoNetJavierLopez.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExamenAdoNetJavierLopez/Controllers/LibrosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExamenAdoNetJavierLopez.Data;
using ExamenAdoNetJavierLopez.Models;

namespace ExamenAdoNetJavierLopez.Controllers
{
    public class LibrosController : Controller
    {
        LibrosContext context;

        public LibrosController()
        {
            this.context = new LibrosContext();
        }

        public IActionResult Libros(int idgenero)
        {
            if (idgenero == 0) { 
            List<Libro> libros = this.context.GetLibros();
            return View(libros);
        }
            else
            {
                List<Libro> libros = this.context.getLibrosporGenero(idgenero);
                return View(libros);
            }
        }
        public IActionResult DetalleLibro(int idlibro)
        {
            Libro lib=this.context.getLibro(idlibro);
            ViewBag.Genero = this.context.getGeneroLibro(idlibro);
            return View(lib);
        }

        public IActionResult Modificalibro(int idlibro)
        {
            Libro lib = this.context.getLibro(idlibro);
            List<Genero> generos = this.context.getGeneros();
            ViewBag.Titulo = lib.Titulo;
            ViewBag.Autor = lib.Autor;
            ViewBag.Sinopsis = lib.Sinopsis;
            ViewBag.Imagen = lib.Imagen;
            ViewBag.Genero = lib.IdGenero;
            ViewBag.Gnombre = this.context.GetGeneroId(lib.IdGenero).Gnombre;
            return View(generos);
        }
        [HttpPost]
        public IActionResult Modificalibro(Libro lib)
        {
            this.context.CambiaLibro(lib.IdLibro, lib.Titulo, lib.Autor, lib.Sinopsis, lib.Imagen, lib.IdGenero);
            return RedirectToAction("Libros");

        }
        public IActionResult CreaLibro()
        {
            List<Genero> generos = this.context.getGeneros();
            return View(generos);
        }
        [HttpPost]
        public IActionResult CreaLibro(Libro lib)
        {
            this.context.createLibro(lib.Titulo,lib.Autor,lib.Sinopsis,lib.Imagen,lib.IdGenero);
            return RedirectToAction("Libros");
        }
    }
}

ExamenAdoNetJavierLopez/Views/Generos/BuscaLibros.cshtml
@model List<Genero>


<h1>Buscador de libros</h1>

<form method="post">
    <label>Género:</label>
    <select name="Gnombre">
        <option value="@ViewBag.GeneroNombre" selected disabled hidden>@ViewBag.GeneroNombre</option>
        @foreach (Genero gen in Model)
        {
            <option value="@gen.Gnombre">@gen.Gnombre</option>
        }
    </select>
    <button type="submit" class="btn btn-light">Buscar</button>
</form>

@if (ViewBag.Libros != null)
{
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Titulo</th>
            <th>Autor</th>
            <th>Detalles</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Libro lib in ViewBag.Libros)
        {
            <tr>
                <td>@lib.Titulo</td>
                <td>@lib.Autor</td>
                <td>@Html.ActionLink("más", "DetalleLibro", "Libros", new { idlibro = lib.IdLibro })</td>
                <td>@Html.ActionLink("Modificar", "Modificalibro", "Libros", new { idlibro = lib.IdLibro })</td>
            </tr>
        }
    </tbody>
</table>
}

ExamenAdoNetJavierLopez/Views/Generos/Genero.cshtml
@model List<Genero>

<h1>Generos</h1>

<div class="btn btn-light" id="enlace">
    @Html.ActionLink("nuevo genero", "creaGenero", "Generos")
</div>
<div class="btn btn-light">@Html.ActionLink("Buscador de libros", "BuscaLibros", "Generos")</div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Genero</th>
                <th>Libros</th>
                <th>Accion</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Genero gen in Model)
            {
                <tr>
                    <td>@gen.Gnombre</td>
                    <td>@Html.ActionLink("Libros", "Libros", "Libros", new { idgenero = gen.IdGenero })</td>

                    <td>
                        @if (gen.IdGenero != -1)
                            @Html.ActionLink("Eliminar", "eliminaGenero", "Generos", new { idgenero = gen.IdGenero })
                    </td>

                </tr>
            }
        </tbody>
    </table>

ExamenAdoNetJavierLopez/Views/Generos/creaGenero.cshtml
<h1>Creacion de Generos</h1>

<form method="post">
    <label>Género:</label>
    <input type="Text" name="Gnombre" class="form-control" />
    <button type="submit">Crear Genero</button>
</form>

ExamenAdoNetJavierLopez/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>
    Biblioteca Alejandría
</h1>

ExamenAdoNetJavierLopez/Views/Libros/CreaLibro.cshtml
@model List<Genero>

<h1>Nuevo Libro</h1>

<form method="post">
    <label>Titulo:</label>
    <input type="text" class="form-control" name="Titulo" />
    <label>Autor:</label>
    <input type="text" name="Autor" class="form-control" />
    <label>Sinopsis:</label>
    <input type="text" name="Sinopsis" class="form-control" />
    <label>Imagen</label>
    <input type="text" name="Imagen" class="form-control"/>
    <br />
    <label>Genero:</label>
    <select name="IdGenero">
        @foreach(Genero gen in Model)
        {
            <option value="@gen.IdGenero">@gen.Gnombre</option>
        }

    </select>
    <button type="submit" class="btn-info">Crear Libro</button>
</form>

ExamenAdoNetJavierLopez/Views/Libros/DetalleLibro.cshtml
@model Libro
<div id="enlace" class="btn btn-light">
    @Html.ActionLink("<--", "Libros", "Libros")
</div>

<div class="container">
    <h1>@Model.Titulo</h1>
    <h2>@Model.Autor</h2>
    <h3>@ViewBag.Genero</h3>
    <img style="width:200px;height:auto" src="~/Images/@Model.Imagen" />
    <p>@Model.Sinopsis</p>
</div>

ExamenAdoNetJavierLopez/Views/Libros/Libros.cshtml
@model List<Libro> 
 
<h1>Libros Disponibles</h1>
<div class="btn btn-light" id="enlace">
    @Html.ActionLink("Nuevo Libro", "CreaLibro", "Libros")
</div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Titulo</th>
                <th>Autor</th>
                <th>Detalles</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Libro lib in Model)
            {
                <tr>
                    <td>@lib.Titulo</td>
                    <td>@lib.Autor</td>
                    <td>@Html.ActionLink("más", "DetalleLibro", "Libros", new { idlibro = lib.IdLibro })</td>
                    <td>@Html.ActionLink("Modificar", "Modificalibro", "Libros", new { idlibro = lib.IdLibro })</td>
                </tr>
            }
        </tbody>
    </table>

ExamenAdoNetJavierLopez/Views/Libros/Modificalibro.cshtml
@model List<Genero>

<h1>Modificar Libro</h1>

<form method="post">
    <label>Titulo:</label>
    <input type="text" class="form-control" name="Titulo" value="@ViewBag.titulo" />
    <label>Autor:</label>
    <input type="text" name="Autor" class="form-control" value="@ViewBag.Autor" />
    <label>Sinopsis:</label>
    <input type="text" name="Sinopsis" class="form-control" value="@ViewBag.Sinopsis" />
    <label>Imagen</label>
    <input type="text" name="Imagen" class="form-control" value="@ViewBag.Imagen"/>
    <br />
    <label>Genero:</label>
    <select name="IdGenero">
        <option value="@ViewBag.Genero" selected disabled hidden >@ViewBag.Gnombre</option>
        @foreach (Genero gen in Model)
        {
            <option value="@gen.IdGenero">@gen.Gnombre</option>
        }

    </select>
    <button type="submit" class="btn-info">Modificar Libro</button>
</form>

@* ViewBag.Titulo = lib.Titulo;
    ViewBag.Autor = lib.Autor;
    ViewBag.Sinopsis = lib.Sinopsis;
    ViewBag.Imagen = lib.Imagen;
    ViewBag.Genero = lib.IdGenero; *@

ExamenAdoNetJavierLopez/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamenAdoNetJavierLopez</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        .container {
            text-align: center;
        }
        #enlace{text-align:left}
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" asp-action="Index" asp-controller="Home">Biblioteca Alejandría</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav mr-auto">
                
                <li class="nav-item">
                    <a class="nav-link" asp-action="Libros" asp-controller="Libros">Libros</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Genero" asp-controller="Generos">Generos</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ExamenAdoNetJavierLopez - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>